FROM centos:7.2.1511
RUN yum -y install gcc make m4 wget tar patch
RUN wget https://www.chef.io/chef/install.sh -O /tmp/install.sh && bash /tmp/install.sh -P chefdk -v 0.17.17
COPY . /root
RUN cd /root && bash vendor.sh
